app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Index
Route::get('/', 'JobsController@index');

//for testing

// Route::get('job_posts/jobview','PagesController@jobview');
// Route::get('job_posts/jobcreate','PagesController@jobcreate');
// Route::get('job_posts/jobedit','PagesController@jobedit');

// Route::get('recommendation/students', 'PagesController@recommendStudents');

// PagesController
Route::get('company/show', 'PagesController@companyShow');
Route::get('dean/show', 'PagesController@deanShow');
Route::get('company/edit', 'PagesController@companyEdit');
Route::get('students/joblists', 'PagesController@jobLists');
Route::get('students/companylists', 'PagesController@companyLists');
Route::get('students/schoollists', 'PagesController@SchoolLists');

Route::get('schools/show','PagesController@schoolShow');
Route::get('schools/edit','PagesController@schoolEdit');

// Route::get('admin/index', 'PagesController@adminIndex');
// Route::get('admin/students', 'PagesController@adminStudentLists');
// Route::get('admin/companies', 'PagesController@adminCompanyLists');
// Route::get('admin/schools', 'PagesController@adminSchoolLists');
// Route::get('admin/faculties', 'PagesController@adminFacultyLists');
// Route::get('admin/jobs', 'PagesController@adminJobLists');
// Route::get('admin/applications', 'PagesController@admingAppLists');
// Route::get('admin/applications', 'PagesController@adminRecommendLists');
// Route::get('admin/categories', 'PagesController@adminCategoryLists');
// Route::get('admin/categories/create', 'PagesController@adminCreateCategories');


// Authentication
Route::get('about', 'PagesController@about');

Route::get('preregister', 'Auth\AuthController@preregister');
Route::post('preregister', 'Auth\AuthController@registerByUserType');
Route::get('register/admin', 'Auth\AuthController@registerAsAdmin');
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister');
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::get('admin/students', 'StudentsController@index');
// Admin Routes
Route::group(['namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::resource('categories', 'CategoriesController');
    Route::get('admin/students', 'StudentsController@index');
    Route::get('admin/schools', 'SchoolsController@index');
    Route::get('admin/faculties', 'FacultiesController@index');
    Route::get('admin/companies', 'CompaniesController@index');
    Route::get('admin/applications', 'ApplicationsController@index');
    Route::get('admin/pending-applications', 'ApplicationsController@showPendingApplications');
    Route::get('admin/successful-applications', 'ApplicationsController@showSuccessfulApplications');
    Route::get('admin/declined-applications', 'ApplicationsController@declinedApplications');
    Route::get('admin/recommendations', 'RecommendationsController@index');
    Route::get('admin/jobs', 'JobsController@index');
    Route::get('admin/active-jobs', 'JobsController@activeJobs');
    Route::get('admin/expired-jobs', 'JobsController@expiredJobs');
    Route::post('admin/jobs/retrieve/{id}', array('as' => 'jobs.retrieve', 'uses' => 'JobsController@retrieve'));
    Route::delete('admin/jobs/destroy/{id}', array('as' => 'jobs.forcedelete', 'uses' => 'JobsController@destroy'));
    Route::delete('admin/jobs/delete/{id}', array('as' => 'jobs.delete', 'uses' => 'JobsController@setJobAsExpired'));
    Route::delete('admin/users/delete/{id}', array('as' => 'admin.delete', 'uses' => 'UsersController@destroy'));
    Route::post('admin/users/retrieve/{id}', array('as' => 'admin.retrieve', 'uses' => 'UsersController@retrieve'));
    Route::delete('admin/users/force-delete/{id}', array('as' => 'admin.forcedelete', 'uses' => 'UsersController@forceDelete'));
});


// NOTE: Resource routes must be at the top of User Routes to avoid being overridden
// Job Posts Routes
Route::post('jobs/apply', ['as' => 'jobs.apply', 'uses' => 'JobsController@apply']);
Route::post('jobs/cancel', ['as' => 'jobs.cancel', 'uses' => 'JobsController@cancelApplication']);
Route::get('jobs/category/{id}', ['as' => 'jobs.category', 'uses' => 'JobsController@getJobsByCategory']);
Route::resource('jobs', 'JobsController');

// Faculty Routes
Route::resource('faculties', 'FacultiesController');

// Student Routes
Route::get('students/skills/{name}', 'StudentsController@studentsBySkill');
Route::resource('students', 'StudentsController');

// Companies Routes
Route::post('companies/partner', ['as' => 'companies.partner', 'uses' => 'CompaniesController@requestPartnership']);
Route::post('companies/accept', ['as' => 'companies.accept', 'uses' => 'CompaniesController@acceptPartnership']);
Route::get('companies/{id}/jobs', ['as' => 'companies.posts', 'uses' => 'CompaniesController@getJobsPosted']);
Route::resource('companies', 'CompaniesController');

// Schools Routes
Route::post('schools/partner', ['as' => 'schools.partner', 'uses' => 'SchoolsController@requestPartnership']);
Route::post('schools/accept', ['as' => 'schools.accept', 'uses' => 'SchoolsController@acceptPartnership']);
Route::resource('schools', 'SchoolsController');

// Application Routes
Route::get('/applications', ['as' => 'application.index', 'uses' => 'ApplicationsController@index']);

// Recommendation Routes
Route::post('recommendations/students', 'RecommendationsController@recommendStudent');
Route::get('recommendations/students', 'RecommendationsController@getStudents');
Route::get('recommendations/student/{id}', 'RecommendationsController@viewRecommendationsOfStudent');
Route::resource('recommendations', 'RecommendationsController');

// Partnership Routes
Route::resource('partnerships', 'PartnershipsController');

// User Routes
Route::get('/{id}', ['as' => 'users.show', 'uses' => 'UserController@show']);
Route::get('/{id}/edit', 'UserController@edit');
Route::put('/{id}', 'UserController@update');


//testin login
// Route::get('login','PagesController@login');
// Route::get('register','PagesController@register');
// Route::get('preregister','PagesController@preregister');
// Route::post('preregister', 'PagesController@userType');

resources/views/admin/_applicationLists.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class=" wrapper-content">
        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                  <h2 class="sidelines-box-header"><span class="fa fa-user-plus"></span> Applications</h2>
                </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Company Name</th>
                            <th>Job Title</th>
                            <th>Student Name</th>
                            <th>Benefits</th>
                            <th>Action</th>
                        </tr>
                      </thead>
                    <tbody>
                        @foreach($applications as $application)
                            <tr>
                                <td> {{ $application->company_name }} </a></td>
                                <td><a href="{{ URL::route('jobs.show', $application->job_id) }}"> {{ $application->name }} </a></td>
                                <td><a href="{{ URL::to('/' . $application->id) }}"> {{ $application->fname . ' ' . $application->lname }} </a></td>
                                <td>
                                    @if($application->major_benefit == '0')
                                            Sponsorship for Tuition Fee
                                    @elseif($application->major_benefit == '1')
                                            Allowance
                                    @elseif($application->major_benefit == '2')
                                            Sponsorship for Tuition Fees + Allowance
                                    @endif
                                </td>
                                <td>
                                    <center>
                                        <a href="{{ URL::route('jobs.show', $application->job_id) }}"><button type="button" class="btn btn-default" title="View"><i class="glyphicon glyphicon-eye-open"></i></button></a>
                                    </center>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/_categoryCreate.blade.php
@extends('layouts.master')
@section('title', 'Sidelines.ph')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="box box-primary">
                        <div class="box-header">
                          <h2 class="sidelines-box-header"><span class="fa fa-plus"></span> Add Category</h2>
                        </div><!-- /.box-header -->
                        <hr/>
                        <div class="box-body">
                            <div class="tab-pane" id="settings">
                                {!! Form::open(array('route' => 'categories.store', 'class' => 'form form-horizontal')) !!}

                                    <div class="form-group">
                                        {!! Form::label('categories', 'Category Name', ['class' => 'col-sm-2 control-label', 'style'=>'margin-top:5px; margin-left:5px;']) !!}
                                        <div class="col-sm-8">
                                            <div class="field_wrapper">
                                                {!! Form::text('category[]', null, ['class' => 'form-control categ-field', 'placeholder' => 'Category','required']) !!}
                                                <a href="javascript:void(0);" class="add_button" title="Add field">
                                                    <i class="glyphicon glyphicon-plus-sign text-green"></i>
                                                </a>
                                            </div>
                                            {!! Form::submit(' Save ',['class'=>'btn btn-primary categ-btn'])!!}
                                        </div>
                                    </div>

                                {!! Form::close() !!}
                            </div><!-- /.tab-pane -->
                        </div> <!-- box-body -->
                    </div> <!-- box -->
                </div>
            <div>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/_categoryEdit.blade.php
@extends('layouts.master')
@section('title', 'Sidelines.ph')

@section('content')

    <link rel="stylesheet" type="text/css" href="{!! asset('dist/css/editprofile.css') !!}">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="box box-primary">
                        <div class="box-header">
                          <h2 class="sidelines-box-header"><span class="fa fa-pencil"></span> Edit Category</h2>
                        </div><!-- /.box-header -->
                        <hr/>
                        <div class="box-body">
                            <div class="tab-pane" id="settings">
                                {!! Form::model($category, array('method' => 'put', 'route' => [ 'categories.update', $category->id], 'class' => 'form form-horizontal')) !!}
                                    <div class="form-group">
                                        {!! Form::label('categories', 'Category Name', ['class' => 'col-sm-2 control-label', 'style'=>'margin-top:5px; margin-left:5px;']) !!}
                                        <div class="col-sm-8">
                                            <div class="field_wrapper">
                                                {!! Form::text('name', $category->name, ['class' => 'form-control categ-field', 'placeholder' => 'Category']) !!}
                                            </div>
                                            {!! Form::submit(' Save ',['class'=>'btn btn-primary categ-btn'])!!}
                                        </div>
                                    </div>

                                {!! Form::close() !!}
                            </div><!-- /.tab-pane -->
                        </div> <!-- box-body -->
                    </div> <!-- box -->
                </div>
            <div>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/_categoryLists.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class=" wrapper-content">
        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                  <h2 class="sidelines-box-header"><span class="fa fa-file-text-o"></span> Job Categories</h2>
                </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Category Name</th>
                            <th>Jobs</th>
                            <th width="200px">Action</th>
                        </tr>
                      </thead>
                    <tbody>
                        @foreach($categories as $id => $category)
                            <tr>
                                <td> {{ $category->name }} </a></td>
                                <td> {{ count($category->jobs) }}</td>
                                <td>
                                    <center>
                                        <a href="{{ URL::route('categories.edit', $category->id)}}"><button type="button" class="btn btn-default" title="Edit"><i class="glyphicon glyphicon-pencil"></i></button></a>
                                        <button type="submit" class="btn btn-default btn-infos" data-toggle="modal" data-target="#model-{{ $id }}" title="Delete"><i class="glyphicon glyphicon-trash"></i></button>

                                        <div class="modal fade" id="model-{{ $id }}" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel" tabindex="">
                                            <div class="modal-dialog box box-danger" >
                                                <div class="modal-content">
                                                  <div class="modal-header-del">
                                                      <h3 class="modal-del-text"><center>This will permanently delete this category in the database.<br/> Are you sure you want to proceed?</center></h3>
                                                  </div>
                                                  <div class="modal-footer">
                                                        <center>
                                                            <div class="action-btns2">
                                                                {!! Form::open(array('route' => array('categories.destroy',  $category->id), 'method' => 'delete')) !!}
                                                                  {!! Form::submit('Yes',['class'=>'btn btn-primary btn-del-yes'])!!}
                                                                {!! Form::close() !!}
                                                            </div>
                                                            <div class="action-btns2">
                                                                <button type="button" class="btn btn-primary btn-del-no" data-toggle="modal" data-target="#model-{{ $id }}">No</button>
                                                            </div>
                                                        </center>
                                                  </div>
                                                </div>
                                            </div>
                                        </div> <!-- modal close-->
                                    </center>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/_jobLists.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class=" wrapper-content">
        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                  <h2 class="sidelines-box-header"><span class="fa fa-newspaper-o"></span> Active Job Posts</h2>
                </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width: 270px; overflow: hidden;">Job Title</th>
                            <th>Company</th>
                            <th>Benefits</th>
                            <th style="width: 86px;">Date Posted</th>
                            <th>Deadline</th>
                            <th>Status</th>
                            <th style="width:150px;">Action</th>
                        </tr>
                      </thead>
                    <tbody>
                        @foreach($jobs as $id => $job)
                            <tr>
                                <td>
                                    <a href="{{ URL::to('/jobs/' . $job->id ) }}" style="overflow: hidden;">
                                        @if(strlen($job->name) > 32)
                                            {{ substr($job->name, 0, 32) . '...'}}
                                        @else
                                            {{ $job->name }}
                                        @endif
                                    </a>
                                </td>
                                <td><a href="{{ URL::route('companies.show', $job->company->id) }}"> {{ $job->company->name }} </a></td>
                                <td>
                                    @if($job->major_benefit == '0')
                                            Sponsorship for Tuition Fee
                                        @elseif($job->major_benefit == '1')
                                            Allowance
                                        @else($job->major_benefit == '2')
                                            Sponsorship for Tuition Fees + Allowance
                                    @endif
                                </td>
                                <td> {{ date("M d, Y", strtotime($job->created_at)) }}</td>
                                <td> {{ date("M d, Y", strtotime($job->deadline_of_application)) }} </td>
                                <td align="center">
                                    @if($job->deleted_at == null)
                                        <small class="label bg-green">Active</small>
                                    @else
                                        <small class="label bg-yellow">Expired</small>
                                    @endif
                                </td>
                                <td>
                                    <div>
                                        <center>
                                            <a href="{{ URL::route('jobs.show', $job->id ) }}" class="btn btn-default" title="View"><i class="glyphicon glyphicon-eye-open"></i></a>
                                            {!! Form::open(array('route' => array('jobs.retrieve', $job->id), 'class'=>'action-btns')) !!}
                                                <button type="submit" class="btn btn-default" title="Retrieve"><i class="glyphicon glyphicon-cloud-upload"></i></button>
                                            {!! Form::close() !!}
                                            {!! Form::open(array('route' => array('jobs.delete', $job->id), 'method' => 'delete', 'method' => 'delete','class'=>'action-btns')) !!}
                                                <button type="submit" class="btn btn-default" title="Deactivate"><i class="glyphicon glyphicon-minus-sign"></i></button>
                                            {!! Form::close() !!}
                                            <button type="submit" class="btn btn-default btn-infos" data-toggle="modal" data-target="#model-{{ $id }}" title="Delete"><i class="glyphicon glyphicon-trash"></i></button>

                                            <div class="modal fade" id="model-{{ $id }}" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel" tabindex="">
                                                <div class="modal-dialog box box-danger" >
                                                    <div class="modal-content">
                                                      <div class="modal-header-del">
                                                          <h3 class="modal-del-text"><center>This will permanently delete this job in the database.<br/> Are you sure you want to proceed?</center></h3>
                                                      </div>
                                                      <div class="modal-footer">
                                                            <center>
                                                                <div class="action-btns2">
                                                                    {!! Form::open(array('route' => array('jobs.forcedelete',  $job->id), 'method' => 'delete')) !!}
                                                                      {!! Form::submit('Yes',['class'=>'btn btn-primary btn-del-yes'])!!}
                                                                    {!! Form::close() !!}
                                                                </div>
                                                                <div class="action-btns2">
                                                                    <button type="button" class="btn btn-primary btn-del-no" data-toggle="modal" data-target="#model-{{ $id }}">No</button>
                                                                </div>
                                                            </center>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div> <!-- modal close-->
                                        </center>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/_recommendLists.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <link rel="stylesheet" type="text/css" href="{!! asset('dist/css/recommend.css') !!}">

<div class=" wrapper-content">
    <!-- Main content -->
    <section class="content">
        <div class="box box-primary">
            <div class="box-header">
              <h2 class="sidelines-box-header"><span class="fa fa-thumbs-up"></span> Recommendations</h2>
            </div><!-- /.box-header -->
          <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Student Name</th>
                        <th>Faculty Name</th>
                        <th>Course</th>
                        <th>Yr Level</th>
                        <th>Action</th>
                    </tr>
                  </thead>
                <tbody>
                    @foreach($students as $student)
                        <tr>
                            <td> {{ $student->student_fname . ' ' . $student->student_lname }} </a></td>
                            <td> {{ $student->faculty_fname . ' ' . $student->faculty_lname }} </a></td>
                            <td> {{ $student->degree_name }} </td>
                            <td align="center">
                                @if($student->yr_lvl != 0)
                                    {{ $student->yr_lvl}}
                                @endif
                            </td>
                            <td>
                                <a href="{{ URL::route('recommendations.show', $student->recommendation_id) }}"> View Details </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

@endsection

resources/views/admin/_sidebarAdmin.blade.php
<li class="header" style="margin-left: -3px;">Actions</li>

    <li>
        <a href="{{ URL::route('categories.create') }}">
            <i class="glyphicon glyphicon-plus text-green"></i> <span class="text-green">Add Category</span>
        </a>
    </li>

<hr class="side-hr"/>

<li class="header" style="margin-left: -3px;">Users</li>

    <li>
        <a href="{{ URL::to('admin/students') }}">
            <i class="fa fa-mortar-board"></i><span> Students </span>
        </a>
    </li>
    <li>
        <a href="{{ URL::to('admin/companies') }}">
            <i class="fa fa-building"></i><span> Companies </span>
        </a>
    </li>
    <li>
        <a href="{{ URL::to('admin/schools') }}">
            <i class="fa fa-university"></i> <span> Schools </span>
        </a>
    </li>
    <li>
        <a href="{{ URL::to('admin/faculties') }}">
            <i class="fa fa-user"></i> <span> Faculties </span>
        </a>
    </li>

<li class="header" style="margin-left: -3px;">Labels</li>

    <li class="treeview">
        <a href="#">
            <i class="fa fa-user-plus"></i> <span>Applications</span> <i class="fa fa-angle-left pull-right"></i>
         </a>
         <ul class="treeview-menu">
            <li><a href="{{ URL::to('admin/pending-applications') }}"><i class="fa fa-circle-o"></i> Pending </a></li>
            <li><a href="{{ URL::to('admin/successful-applications') }}"><i class="fa fa-circle-o"></i> Hired Students</a></li>
            <li><a href="{{ URL::to('admin/declined-applications') }}"><i class="fa fa-circle-o"></i> Declined Students</a></li>
        </ul>
    </li>
    <li>
        <a href="{{ URL::route('categories.index') }}">
            <i class="fa fa-file-text-o"></i><span> Categories </span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-clipboard"></i> <span>Job Posts</span> <i class="fa fa-angle-left pull-right"></i>
         </a>
         <ul class="treeview-menu">
            <li class="#"><a href="{{ URL::to('admin/active-jobs') }}"><i class="fa fa-circle-o"></i> Active </a></li>
            <li><a href="{{ URL::to('admin/expired-jobs') }}"><i class="fa fa-circle-o"></i> Expired </a></li>
        </ul>
    </li>
    <li>
        <a href="{{ URL::to('admin/recommendations') }}">
            <i class="fa fa-thumbs-up"></i><span> Recommendations </span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-users"></i><span> Partners </span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-money"></i><span> Payments </span>
        </a>
    </li>

resources/views/admin/index.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="wrapper-content">
        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">
              <div class="box-header">
                <h3 class="box-title">Jobs Applieds</h3>
              </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Job Title</th>
                            <th>Location</th>
                            <th>Company</th>
                            <th>Benefits</th>
                            <th>Date Posted</th>
                            <th>Action</th>
                        </tr>
                      </thead>
                    <tbody>
                        <tr>
                            <td><a href="#"> Accenture </a></td>
                            <td>Cebu City, Cebu <small class="text-muted"> 795 Folsom Ave, Suite 600 <small></td>
                            <td>Admin, Inc.</td>
                            <td> Tuition Fee  Sponsorship + Allowance </td>
                            <td> November 10 </td>
                            <td>
                                <center>
                                    <a href="#"><button type="button" class="btn btn-default" title="View"><i class="glyphicon glyphicon-eye-open"></i></button></a>
                                    <a href="#"><button type="button" class="btn btn-default" title="Edit"><i class="glyphicon glyphicon-pencil"></i></button></a>
                                    <a href="#"><button type="button" class="btn btn-default" title="Delete"><i class="glyphicon glyphicon-trash"></i></button></a>
                                </center>
                            </td>
                        </tr>
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection