app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Index
Route::get('/', 'JobsController@index');

//for testing

// Route::get('job_posts/jobview','PagesController@jobview');
// Route::get('job_posts/jobcreate','PagesController@jobcreate');
// Route::get('job_posts/jobedit','PagesController@jobedit');

// Route::get('recommendation/students', 'PagesController@recommendStudents');

// PagesController
Route::get('company/show', 'PagesController@companyShow');
Route::get('dean/show', 'PagesController@deanShow');
Route::get('company/edit', 'PagesController@companyEdit');
Route::get('students/joblists', 'PagesController@jobLists');
Route::get('students/companylists', 'PagesController@companyLists');
Route::get('students/schoollists', 'PagesController@SchoolLists');

Route::get('schools/show','PagesController@schoolShow');
Route::get('schools/edit','PagesController@schoolEdit');

// Route::get('admin/index', 'PagesController@adminIndex');
// Route::get('admin/students', 'PagesController@adminStudentLists');
// Route::get('admin/companies', 'PagesController@adminCompanyLists');
// Route::get('admin/schools', 'PagesController@adminSchoolLists');
// Route::get('admin/faculties', 'PagesController@adminFacultyLists');
// Route::get('admin/jobs', 'PagesController@adminJobLists');
// Route::get('admin/applications', 'PagesController@admingAppLists');
// Route::get('admin/applications', 'PagesController@adminRecommendLists');
// Route::get('admin/categories', 'PagesController@adminCategoryLists');
// Route::get('admin/categories/create', 'PagesController@adminCreateCategories');


// Authentication
Route::get('about', 'PagesController@about');

Route::get('preregister', 'Auth\AuthController@preregister');
Route::post('preregister', 'Auth\AuthController@registerByUserType');
Route::get('register/admin', 'Auth\AuthController@registerAsAdmin');
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister');
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::get('admin/students', 'StudentsController@index');
// Admin Routes
Route::group(['namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::resource('categories', 'CategoriesController');
    Route::get('admin/students', 'StudentsController@index');
    Route::get('admin/schools', 'SchoolsController@index');
    Route::get('admin/faculties', 'FacultiesController@index');
    Route::get('admin/companies', 'CompaniesController@index');
    Route::get('admin/applications', 'ApplicationsController@index');
    Route::get('admin/pending-applications', 'ApplicationsController@showPendingApplications');
    Route::get('admin/successful-applications', 'ApplicationsController@showSuccessfulApplications');
    Route::get('admin/declined-applications', 'ApplicationsController@declinedApplications');
    Route::get('admin/recommendations', 'RecommendationsController@index');
    Route::get('admin/jobs', 'JobsController@index');
    Route::get('admin/active-jobs', 'JobsController@activeJobs');
    Route::get('admin/expired-jobs', 'JobsController@expiredJobs');
    Route::post('admin/jobs/retrieve/{id}', array('as' => 'jobs.retrieve', 'uses' => 'JobsController@retrieve'));
    Route::delete('admin/jobs/destroy/{id}', array('as' => 'jobs.forcedelete', 'uses' => 'JobsController@destroy'));
    Route::delete('admin/jobs/delete/{id}', array('as' => 'jobs.delete', 'uses' => 'JobsController@setJobAsExpired'));
    Route::delete('admin/users/delete/{id}', array('as' => 'admin.delete', 'uses' => 'UsersController@destroy'));
    Route::post('admin/users/retrieve/{id}', array('as' => 'admin.retrieve', 'uses' => 'UsersController@retrieve'));
    Route::delete('admin/users/force-delete/{id}', array('as' => 'admin.forcedelete', 'uses' => 'UsersController@forceDelete'));
});


// NOTE: Resource routes must be at the top of User Routes to avoid being overridden
// Job Posts Routes
Route::post('jobs/apply', ['as' => 'jobs.apply', 'uses' => 'JobsController@apply']);
Route::post('jobs/cancel', ['as' => 'jobs.cancel', 'uses' => 'JobsController@cancelApplication']);
Route::get('jobs/category/{id}', ['as' => 'jobs.category', 'uses' => 'JobsController@getJobsByCategory']);
Route::resource('jobs', 'JobsController');

// Faculty Routes
Route::resource('faculties', 'FacultiesController');

// Student Routes
Route::get('students/skills/{name}', 'StudentsController@studentsBySkill');
Route::resource('students', 'StudentsController');

// Companies Routes
Route::post('companies/partner', ['as' => 'companies.partner', 'uses' => 'CompaniesController@requestPartnership']);
Route::post('companies/accept', ['as' => 'companies.accept', 'uses' => 'CompaniesController@acceptPartnership']);
Route::get('companies/{id}/jobs', ['as' => 'companies.posts', 'uses' => 'CompaniesController@getJobsPosted']);
Route::resource('companies', 'CompaniesController');

// Schools Routes
Route::post('schools/partner', ['as' => 'schools.partner', 'uses' => 'SchoolsController@requestPartnership']);
Route::post('schools/accept', ['as' => 'schools.accept', 'uses' => 'SchoolsController@acceptPartnership']);
Route::resource('schools', 'SchoolsController');

// Application Routes
Route::get('/applications', ['as' => 'application.index', 'uses' => 'ApplicationsController@index']);

// Recommendation Routes
Route::post('recommendations/students', 'RecommendationsController@recommendStudent');
Route::get('recommendations/students', 'RecommendationsController@getStudents');
Route::get('recommendations/student/{id}', 'RecommendationsController@viewRecommendationsOfStudent');
Route::resource('recommendations', 'RecommendationsController');

// Partnership Routes
Route::resource('partnerships', 'PartnershipsController');

// User Routes
Route::get('/{id}', ['as' => 'users.show', 'uses' => 'UserController@show']);
Route::get('/{id}/edit', 'UserController@edit');
Route::put('/{id}', 'UserController@update');


//testin login
// Route::get('login','PagesController@login');
// Route::get('register','PagesController@register');
// Route::get('preregister','PagesController@preregister');
// Route::post('preregister', 'PagesController@userType');

app/Http/Controllers/Admin/RecommendationsController.php
<?php

namespace sidelines\Http\Controllers\Admin;

use Illuminate\Http\Request;

use sidelines\Http\Requests;
use sidelines\Http\Controllers\Controller;

class RecommendationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = \DB::table('students')
                        ->join('recommendations', 'recommendations.student_id', '=', 'students.id')
                        ->join('degrees', 'degrees.id', '=', 'students.degree_id')
                        ->join('dean_faculties', 'dean_faculties.id', '=', 'recommendations.dean_faculty_id')
                        ->select('degrees.name as degree_name', 'students.lname as student_lname', 'students.fname as student_fname',
                                'students.yr_lvl', 'degrees.name as degree', 'dean_faculties.lname as faculty_lname', 'dean_faculties.fname as faculty_fname', 'recommendations.id as recommendation_id')
                        ->get();
                        // dd($students);
        return view('admin._recommendLists', compact('students'));
    }
}

app/Http/Controllers/RecommendationsController.php
<?php

namespace sidelines\Http\Controllers;

use Illuminate\Http\Request;

use sidelines\Student;
use sidelines\DeanFaculty;
use sidelines\Http\Requests;
use sidelines\Http\Controllers\Controller;

class RecommendationsController extends Controller
{
    public function __construct()
    {
        $this->middleware('recommendation', ['only' => ['edit', 'getStudents']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(\Auth::user()->user_type === 'd' || \Auth::user()->user_type === 'f')
        {
            $students = \Auth::user()->userable->recommendations;
            // dd($students);
            return view('recommendation.index', compact('students'));
        }
        else if(\Auth::user()->user_type === 'c')
        {
            $students = \DB::table('students')
                            ->join('recommendations', 'recommendations.student_id', '=', 'students.id')
                            ->join('degrees', 'degrees.id', '=', 'students.degree_id')
                            ->join('users', 'users.userable_id', '=', 'students.id')
                            ->select('users.id as user_id', 'students.id', 'students.lname', 'students.fname', 'students.yr_lvl', 'degrees.name as degree', \DB::raw('count(recommendations.student_id) as recommendations'))
                            ->where('users.user_type', '=', 's')
                            ->groupBy('recommendations.student_id')
                            ->get();
                            // dd($students);
            return view('recommendation.index', compact('students'));
            // dd($students);
        }
        else if(\Auth::user()->user_type === 's'){

            $faculties = \Auth::user()->userable->recommendations;

            return view('recommendation.index', compact('faculties'));
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!\Auth::user()->userable->recommendations->contains($request['student_id']))
        {
            \Auth::user()->userable->recommendations()
                ->attach(array($request['student_id'] => array('recommendation_details' => $request['recommendation_letter'])));
        }

        return \Redirect::route('recommendations.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // if(\Auth::user()->user_type === 'd' || \Auth::user()->user_type === 'f')
        // {
        //     $student = \Auth::user()->userable->recommendations()->where('student_id', $id)->first();
        //
        //     return view('recommendation.show', compact('student'));
        // }
        // else
        // {
            $recommendation = \DB::table('recommendations')->where('id', $id)->get();

            $faculty = DeanFaculty::find($recommendation[0]->dean_faculty_id);
            $student = $faculty->recommendations()->where('student_id', $recommendation[0]->student_id)->first();

            return view('recommendation.show', compact('student'));
        // }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = \Auth::user()->userable->recommendations()->where('student_id', $id)->first();

        return view('recommendation.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $student = \Auth::user()->userable->recommendations()->where('student_id', $id)->first();
        // dd($request);
        \Auth::user()->userable->recommendations()
            ->updateExistingPivot($id, array('recommendation_details' => $request['recommendation_details']));

        return \Redirect::route('recommendations.show', $request['recommendation_id']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    // Custom methods

    public function getStudents()
    {
        $students = Student::where('school_id', \Auth::user()->userable->school_id)->get();

        return view('recommendation.students', compact('students'));
    }

    public function recommendStudent(Request $request)
    {
        $student = Student::find($request['student_id']);

        return view('recommendation.create', compact('student'));
    }

    public function viewRecommendationsOfStudent($id)
    {
        $student = Student::with('recommendations')->find($id);
        $faculties = $student->recommendations;
        // dd($faculties);
        return view('recommendation.viewrecommendations', compact('faculties', 'student'));
    }
}

resources/views/recommendation/create.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <link rel="stylesheet" type="text/css" href="{!! asset('dist/css/recommend.css') !!}">

    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content-header">
            <h3></h3>
        </section>
        <section class="content jobpost-content">
            <div class="row ">
                <div class="col-md-10 col-md-offset-1">
                    <div class="box box-primary color-palette-box">
                        <div class="box-header">
                          <h2 class="sidelines-box-header"><span class="fa  fa-check-square-o"></span> Recommend {{ current(explode(' ',$student->fname)) . ' ' . $student->lname }}</h2>
                        </div><!-- /.box-header -->
                      <div class="box-body">


                            <div class="jobpost-label">
                                <br/>
{!! Form::open(array('route' => 'recommendations.store')) !!}
                                <!-- if -->

                                @if(!empty($student->degree->name) && $student->degree->name != null)

                                {!! Form::textarea('recommendation_letter','

Dear Sir/Madam,

Hello and good day!

I would like to recommend ' .  $student->fname . ' ' . $student->lname . ' to your company.
He is from '. $student->school->name . ' currently taking up ' . $student->degree->name . '.

[Reason why you recommend this student. (e.g. Skills, Achievements or Character)]

Thank you very much.

Sincerely yours,

'  .

Auth::user()->userable->fname . ' ' . Auth::user()->userable->lname

                                 , ['class' => 'form-control jobcreate-desc','required']) !!}

                                @else

                                {!! Form::textarea('recommendation_letter','

Dear Sir/Madam,

Hello and good day!

I would like to recommend ' .  $student->fname . ' ' . $student->lname . ' to your company.

[Reason why you recommend this student. (e.g. Skills, Achievements or Character)]

Thank you very much.

Sincerely yours,

'  .

Auth::user()->userable->fname . ' ' . Auth::user()->userable->lname

                                , ['class' => 'form-control jobcreate-desc','required']) !!}

                                @endif

                                <!-- endif -->

                            </div>

                            <div class="jobpost-label"><center>
                                {!! Form::hidden('student_id', $student->id) !!}
                                {!! Form::submit('Send Recommendation',['class'=>'btn btn-primary'])!!}
                                <a href="{{ URL::to('recommendations/students') }}" class="btn btn-danger btn-cancel" > Cancel </a>
                            </div></center><br/>
{!! Form::close() !!}

                       </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!--col-->
            </div><!--row-->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/recommendation/edit.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <link rel="stylesheet" type="text/css" href="{!! asset('dist/css/recommend.css') !!}">

    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content-header">
            <h3></h3>
        </section>
        <section class="content jobpost-content">
            <div class="row ">
                <div class="col-md-10 col-md-offset-1">
                    <div class="box box-primary color-palette-box">
                        <div class="box-header">
                          <h2 class="sidelines-box-header"><span class="fa  fa-check-square-o"></span> Recommendation of {{ current(explode(' ',$student->fname)) . ' ' . $student->lname }}</h2>
                        </div><!-- /.box-header -->
                      <div class="box-body">


                            <div class="jobpost-label">
                                <br/>
                            {!! Form::model($student->pivot, array('method' => 'put',
                                'route' => ['recommendations.update',  $student->id])) !!}

                                {!! Form::textarea('recommendation_details', null , ['class' => 'form-control jobcreate-desc','required']) !!}

                            </div>

                            <div class="jobpost-label"><center>
                                {!! Form::hidden('recommendation_id', $student->pivot->id) !!}
                                {!! Form::submit(' Save Changes ',['class'=>'btn btn-primary'])!!}
                                <a href="{{ URL::to('recommendations/students') }}" class="btn btn-danger btn-cancel" > Cancel </a>
                            </div></center><br/>
                            {!! Form::close() !!}
                       </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!--col-->
            </div><!--row-->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/recommendation/index.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <link rel="stylesheet" type="text/css" href="{!! asset('dist/css/recommend.css') !!}">

    @if(Auth::user()->user_type == 'd' || Auth::user()->user_type == 'f')

    <div class=" wrapper-content ">
        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                  <h2 class="sidelines-box-header"><span class="fa fa-thumbs-up"></span>Recommended Students</h2>
                </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th width="20px"></th>
                            <th>Name</th>
                            <th>Course</th>
                            <th style="width: 80px;" >Year Level</th>
                            <th style="width: 75px;"></th>
                        </tr>
                      </thead>
                    <tbody>
                        @foreach($students as $student)
                            <tr>
                                <td>
                                    <div class="user-block">
                                        @if($student->user != null)
                                            @if(!empty($student->user->image))
                                                <img src="{{ asset('img/profilepics/' . $student->user->image) }}" class="img-circle" alt="User Image">
                                            @else
                                                <img src="{{ asset('dist/img/avatar-default.png') }}" class="img-circle" alt="User Image">
                                            @endif
                                        @endif
                                    </div><!-- /.user-block -->
                                </td>
                                <td>
                                    @if($student->user != null)
                                        <a href="{{ URL::to('/', $student->user->id) }}"> {{ $student->fname . ' ' . $student->lname }} </a>
                                    @else
                                        {{ $student->fname . ' ' . $student->lname }}
                                    @endif
                                </td>
                                <td>
                                    @if(!empty($student->degree->name) && $student->degree->name != null)
                                        {{ $student->degree->name }}
                                    @else
                                        None
                                    @endif
                                </td>
                                <td align="center">
                                    @if($student->yr_lvl != 0)
                                        {{ $student->yr_lvl}}
                                    @else
                                        None
                                    @endif
                                </td>
                                <td align="center">
                                    <a href="{{ URL::route('recommendations.show', $student->pivot->id) }}"> View Details </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @elseif(Auth::user()->user_type == 'c')

    <div class=" wrapper-content ">
        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                  <h2 class="sidelines-box-header"><span class="fa fa-list"></span> Recommended Students</h2>
                </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th width="8px"> </th>
                            <th style="width: 150px;"></th>
                            <th>Name</th>
                            <th>Course</th>
                            <th style="width: 80px;">Year Level</th>
                        </tr>
                      </thead>
                    <tbody>
                        @foreach($students as $student)
                            <tr>
                                <td>
                                    <center>
                                        <small class="label bg-green" title="Recommendations"> {{ $student->recommendations }} </small>
                                    </center>
                                </td>
                                <td>
                                    <a href="{{ URL::to('recommendations/student/' . $student->id) }}" style="font-size: 14px;"> View Recommendations </a>
                                </td>
                                <td>
                                    <a href="{{ URL::to('/', $student->user_id) }}"> {{ $student->fname . ' ' . $student->lname }} </a>
                                </td>
                                <td>
                                    @if(!empty($student->degree) && $student->degree != null)
                                        {{ $student->degree }}
                                    @endif
                                </td>
                                <td align="center">
                                    @if($student->yr_lvl != 0)
                                        {{ $student->yr_lvl}}
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @elseif(Auth::user()->user_type == 's')

    <div class=" wrapper-content ">
        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                  <h2 class="sidelines-box-header"><span class="fa fa-thumbs-up"></span> My Recommendations</h2>
                </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th width="20px"></th>
                            <th>Faculty Name</th>
                            <th>Date Recommended</th>
                            <th width="80px"></th>
                        </tr>
                      </thead>
                    <tbody>
                        @foreach($faculties as $faculty)
                            <tr>
                                <td>
                                    <div class="user-block">
                                        @if(!empty($faculty->user->image))
                                            <img src="{{ asset('img/profilepics/' . $faculty->user->image) }}" class="img-circle" alt="User Image">
                                        @else
                                            <img src="{{ asset('dist/img/avatar-default.png') }}" class="img-circle" alt="User Image">
                                        @endif
                                    </div><!-- /.user-block -->
                                </td>
                                <td><a href="{{ route('users.show', $faculty->user->id) }}"> {{ $faculty->fname . ' ' . $faculty->lname}} </a></td>
                                <td> {{ date("M d, Y", strtotime($faculty->pivot->created_at)) }} </td>
                                <td align="center"><a href="{{ URL::route('recommendations.show', $faculty->pivot->id) }}">View Details</a></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @endif
@endsection

resources/views/recommendation/show.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <link rel="stylesheet" type="text/css" href="{!! asset('dist/css/recommend.css') !!}">

    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content-header">
            <h3></h3>
        </section>
        <section class="content jobpost-content">
            <div class="row ">
                <div class="col-md-10 col-md-offset-1">
                    <div class="box box-primary color-palette-box">
                        <div class="box-header">
                          <h2 class="sidelines-box-header"><span class="fa  fa-check-square-o"></span> Recommendation of {{ current(explode(' ',$student->fname)) . ' ' . $student->lname }}</h2>
                        </div><!-- /.box-header -->
                      <div class="box-body">


                            <div class="jobpost-label">
                                <br/>

                                <p class="jobpost-p">{!! nl2br(e($student->pivot->recommendation_details)) !!}</p>

                            </div>
                            @if(Auth::user()->user_type === 'd' || Auth::user()->user_type === 'f')
                                @if(Auth::user()->userable->id === $student->pivot->dean_faculty_id)
                                    <div class="jobpost-label"><center>
                                        <a href="{{ URL::route('recommendations.edit',$student->id) }}" class="btn btn-primary" > Edit Details </a>
                                        <a href="{{ URL::route('recommendations.index') }}" class="btn btn-danger btn-cancel" > Cancel </a>
                                    </div></center><br/>
                                @endif
                            @elseif(Auth::user()->user_type === 'c')
                            <div class="jobpost-label"><center>
                                <a href="{{ URL::to('/',$student->user->id) }}" class="btn btn-primary" >    View {{ current(explode(' ',$student->fname)) . '\'s' }} Profile   </a>
                            </div></center><br/>
                            @endif
                       </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!--col-->
            </div><!--row-->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection