app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Index
Route::get('/', 'JobsController@index');

//for testing

// Route::get('job_posts/jobview','PagesController@jobview');
// Route::get('job_posts/jobcreate','PagesController@jobcreate');
// Route::get('job_posts/jobedit','PagesController@jobedit');

// Route::get('recommendation/students', 'PagesController@recommendStudents');

// PagesController
Route::get('company/show', 'PagesController@companyShow');
Route::get('dean/show', 'PagesController@deanShow');
Route::get('company/edit', 'PagesController@companyEdit');
Route::get('students/joblists', 'PagesController@jobLists');
Route::get('students/companylists', 'PagesController@companyLists');
Route::get('students/schoollists', 'PagesController@SchoolLists');

Route::get('schools/show','PagesController@schoolShow');
Route::get('schools/edit','PagesController@schoolEdit');

// Route::get('admin/index', 'PagesController@adminIndex');
// Route::get('admin/students', 'PagesController@adminStudentLists');
// Route::get('admin/companies', 'PagesController@adminCompanyLists');
// Route::get('admin/schools', 'PagesController@adminSchoolLists');
// Route::get('admin/faculties', 'PagesController@adminFacultyLists');
// Route::get('admin/jobs', 'PagesController@adminJobLists');
// Route::get('admin/applications', 'PagesController@admingAppLists');
// Route::get('admin/applications', 'PagesController@adminRecommendLists');
// Route::get('admin/categories', 'PagesController@adminCategoryLists');
// Route::get('admin/categories/create', 'PagesController@adminCreateCategories');


// Authentication
Route::get('about', 'PagesController@about');

Route::get('preregister', 'Auth\AuthController@preregister');
Route::post('preregister', 'Auth\AuthController@registerByUserType');
Route::get('register/admin', 'Auth\AuthController@registerAsAdmin');
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister');
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::get('admin/students', 'StudentsController@index');
// Admin Routes
Route::group(['namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::resource('categories', 'CategoriesController');
    Route::get('admin/students', 'StudentsController@index');
    Route::get('admin/schools', 'SchoolsController@index');
    Route::get('admin/faculties', 'FacultiesController@index');
    Route::get('admin/companies', 'CompaniesController@index');
    Route::get('admin/applications', 'ApplicationsController@index');
    Route::get('admin/pending-applications', 'ApplicationsController@showPendingApplications');
    Route::get('admin/successful-applications', 'ApplicationsController@showSuccessfulApplications');
    Route::get('admin/declined-applications', 'ApplicationsController@declinedApplications');
    Route::get('admin/recommendations', 'RecommendationsController@index');
    Route::get('admin/jobs', 'JobsController@index');
    Route::get('admin/active-jobs', 'JobsController@activeJobs');
    Route::get('admin/expired-jobs', 'JobsController@expiredJobs');
    Route::post('admin/jobs/retrieve/{id}', array('as' => 'jobs.retrieve', 'uses' => 'JobsController@retrieve'));
    Route::delete('admin/jobs/destroy/{id}', array('as' => 'jobs.forcedelete', 'uses' => 'JobsController@destroy'));
    Route::delete('admin/jobs/delete/{id}', array('as' => 'jobs.delete', 'uses' => 'JobsController@setJobAsExpired'));
    Route::delete('admin/users/delete/{id}', array('as' => 'admin.delete', 'uses' => 'UsersController@destroy'));
    Route::post('admin/users/retrieve/{id}', array('as' => 'admin.retrieve', 'uses' => 'UsersController@retrieve'));
    Route::delete('admin/users/force-delete/{id}', array('as' => 'admin.forcedelete', 'uses' => 'UsersController@forceDelete'));
});


// NOTE: Resource routes must be at the top of User Routes to avoid being overridden
// Job Posts Routes
Route::post('jobs/apply', ['as' => 'jobs.apply', 'uses' => 'JobsController@apply']);
Route::post('jobs/cancel', ['as' => 'jobs.cancel', 'uses' => 'JobsController@cancelApplication']);
Route::get('jobs/category/{id}', ['as' => 'jobs.category', 'uses' => 'JobsController@getJobsByCategory']);
Route::resource('jobs', 'JobsController');

// Faculty Routes
Route::resource('faculties', 'FacultiesController');

// Student Routes
Route::get('students/skills/{name}', 'StudentsController@studentsBySkill');
Route::resource('students', 'StudentsController');

// Companies Routes
Route::post('companies/partner', ['as' => 'companies.partner', 'uses' => 'CompaniesController@requestPartnership']);
Route::post('companies/accept', ['as' => 'companies.accept', 'uses' => 'CompaniesController@acceptPartnership']);
Route::get('companies/{id}/jobs', ['as' => 'companies.posts', 'uses' => 'CompaniesController@getJobsPosted']);
Route::resource('companies', 'CompaniesController');

// Schools Routes
Route::post('schools/partner', ['as' => 'schools.partner', 'uses' => 'SchoolsController@requestPartnership']);
Route::post('schools/accept', ['as' => 'schools.accept', 'uses' => 'SchoolsController@acceptPartnership']);
Route::resource('schools', 'SchoolsController');

// Application Routes
Route::get('/applications', ['as' => 'application.index', 'uses' => 'ApplicationsController@index']);

// Recommendation Routes
Route::post('recommendations/students', 'RecommendationsController@recommendStudent');
Route::get('recommendations/students', 'RecommendationsController@getStudents');
Route::get('recommendations/student/{id}', 'RecommendationsController@viewRecommendationsOfStudent');
Route::resource('recommendations', 'RecommendationsController');

// Partnership Routes
Route::resource('partnerships', 'PartnershipsController');

// User Routes
Route::get('/{id}', ['as' => 'users.show', 'uses' => 'UserController@show']);
Route::get('/{id}/edit', 'UserController@edit');
Route::put('/{id}', 'UserController@update');


//testin login
// Route::get('login','PagesController@login');
// Route::get('register','PagesController@register');
// Route::get('preregister','PagesController@preregister');
// Route::post('preregister', 'PagesController@userType');

app/Company.php
<?php

namespace sidelines;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    // The attributes that are mass assignable.
    protected $fillable = ['name', 'description', 'address', 'country', 'zipcode', 'tel_no', 'website'];

    public function user() {
        return $this->morphOne('sidelines\User', 'userable');
    }

    public function jobs()
    {
        return $this->hasMany('sidelines\Job');
    }

    public function partners()
    {
        return $this->belongsToMany('sidelines\School', 'partnerships')
                    ->withPivot('status')
                    ->withTimestamps();
    }
}

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace sidelines\Http\Controllers\Admin;

use Illuminate\Http\Request;

use sidelines\Company;
use sidelines\Http\Requests;
use sidelines\Http\Controllers\Controller;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::with('user')->get();

        return view('admin._companyLists', compact('companies'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);

        $company->user->destroy();
        $company->destroy();
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace sidelines\Http\Controllers;

use Illuminate\Http\Request;

use sidelines\Http\Requests;
use sidelines\Http\Controllers\Controller;
use sidelines\Company;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();

        return view('companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);

        return view('companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);

        return view('companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::find($id);

        if(count($request->all()) > 0)
        {
            if(!empty($request->file('image')))
            {
                $image = $request->file('image');
                $filename  = time() . rand(1, 9999) . '.' . $image->getClientOriginalExtension();

                $request->file('image')->move(
                    base_path() . '/public/img/profilepics', $filename //pass to image field
                );

                $company->user->update([
                    'image' => $filename,
                ]);

                dd($filename);
            }
        }

        $company->user->update([
            'email' => $request['email'],
        ]);

        $company->update($request->all());

        return \Redirect::route('companies.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getJobsPosted($id)
    {
        $company = Company::with('jobs')->find($id);

        if($company != null)
        {
            $jobs = $company->jobs;
            return view('companies.jobPost', compact('jobs'));
        }
        else
        {
            return \Redirect::route('companies.index');
        }
        // TODO: return view('')->with('jobs_posted', $company->jobs);
    }

    public function requestPartnership(Request $request)
    {
        \Auth::user()->userable->partners()->attach(array($request['school_id'] => array('status' => 2)));

        return \Redirect::route('schools.index');
    }

    public function acceptPartnership(Request $request)
    {
        \Auth::user()->userable->partners()->updateExistingPivot($request['school_id'], array('status' => 1));

        return \Redirect::route('schools.index');
    }
}

resources/views/companies/_sidebarCompany.blade.php
<li class="header" style="margin-left: -3px;">Actions</li>

<li>
    <a href="{{ URL::to('/jobs/create') }}">
        <i class="glyphicon glyphicon-plus text-green"></i> <span class="text-green">Post a Job</span>
    </a>
</li>

<hr class="side-hr"/>

<li class="header" style="margin-left: -3px;">Labels</li>

<li>
    <a href="{{ URL::route('companies.posts', Auth::user()->userable->id) }}">
        <i class="fa fa-list-ol"></i> <span> Jobs Posted </span>
    </a>
</li>
<li class="#">
    <a href="{{ URL::route('recommendations.index') }}">
         <i class="fa fa-thumbs-up"></i><span> Recommended Students </span>
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-calendar-check-o"></i> <span> Hired Students </span>
    </a>
</li>
<li>
    <a href="{{ URL::route('companies.index') }}">
        <i class="fa fa-building"></i> <span> Companies </span>
    </a>
</li>
<li>
    <a href="{{ URL::route('schools.index') }}">
        <i class="fa fa-university"></i> <span> Schools </span>
    </a>
</li>
<li>
    <a href="{{ URL::route('partnerships.index') }}">
        <i class="fa fa-users"></i><span> Partners </span>
    </a>
</li>

resources/views/companies/edit.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')

    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit Profile</h3>
                        </div>
                        <div class="box-body">
                            <div class="tab-pane" id="settings">
                                {!! Form::model($company, array('method' => 'put',
                                                             'route' => ['companies.update', $company->id],
                                                             'class' => 'form form-horizontal',
                                                             'files' => 'true')) !!}


                                <div class="form-group">
                                    {!! Form::label('profile', 'Profile Picture', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-4">
                                        <img class="img-responsive thumbnail" src="{{ asset('img/profilepics/' . $company->user->image) }}" alt="User profile picture">
                                        {!! Form::file('image') !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    {!! Form::label('company_name', 'Company Name', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                        {!! Form::text('company_name', $company->name, ['class' => 'form-control', 'placeholder' => 'Company Name']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    {!! Form::label('description', 'Company Description', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                        {!! Form::textarea('description', $company->description, ['class' => 'form-control textarea-desc', 'placeholder' => 'Company Description']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    {!! Form::label('address', 'Company Address', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                        {!! Form::text('address', $company->address, ['class' => 'form-control', 'placeholder' => 'Company Address']) !!}
                                    </div>
                                </div>

                                <div class="form-group">
                                    {!! Form::label('email', 'Email', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                         {!! Form::text('email', $company->user->email, ['class' => 'form-control', 'placeholder' => 'Email']) !!}
                                    </div>
                                 </div>

                                <div class="form-group">
                                    {!! Form::label('country', 'Country', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                        {!! Form::text('country', $company->country, ['class' => 'form-control', 'placeholder' => 'Country']) !!}
                                    </div>
                                </div>
                                <div class="form-group">
                                    {!! Form::label('zipcode', 'Zip Code', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                        {!! Form::text('zipcode', $company->zipcode, ['class' => 'form-control', 'placeholder' => 'Zip Code']) !!}
                                    </div>
                                </div>

                                <div class="form-group">
                                    {!! Form::label('tel_no', 'Contact Number', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                        {!! Form::text('tel_no', $company->tel_no, ['class' => 'form-control', 'placeholder' => 'Contact Number']) !!}
                                    </div>
                                </div>


                                <div class="form-group">
                                    {!! Form::label('website', 'Website', ['class' => 'col-sm-2 control-label']) !!}
                                    <div class="col-sm-9">
                                        {!! Form::text('website', null, ['class' => 'form-control', 'placeholder' => 'Website']) !!}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        {!! Form::submit('Save',['class' => 'btn btn-danger btn-save']) !!}
                                    </div>
                                </div>
                              {!! Form::close() !!}
                            </div><!-- /.tab-pane -->
                        </div> <!-- box-body -->
                    </div> <!-- box -->
                </div>
            </div>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

@endsection

resources/views/companies/index.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class=" wrapper-content ">
        <!-- Main content -->

        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                  <h2 class="sidelines-box-header"><span class="fa fa-building"></span> Companies</h2>
                </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th width="20px"></th>
                            <th>Company Name</th>
                            <th>Location</th>
                            <th style="width: 135px;">Contact Number</th>
                            @if(Auth::user()->user_type == 'sa')
                                <th width="100px"> </th>
                            @endif
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($companies as $id => $company)
                            <tr>
                                <td>
                                    <div class="user-block">
                                        @if(!empty($company->user->image))
                                            <img src="{{ asset('img/profilepics/' . $company->user->image) }}" class="img-circle" alt="User Image">
                                        @else
                                            <img src="{{ asset('dist/img/avatar-default-company.png') }}" class="img-circle" alt="User Image">
                                        @endif
                                    </div><!-- /.user-block -->
                                </td>
                                <td><a href="{{ URL::route('companies.show', $company->id) }}"> {{ $company->name }} </a></td>
                                <td> {{ $company->address }} </td>
                                <td> {{ $company->tel_no }} </td>
                                @if(Auth::user()->user_type == 'sa')
                                    <td>
                                        <center>
                                            @if(Auth::user()->userable->partners->contains($company->id))
                                                @if($company->partners->find(Auth::user()->userable->id)->pivot->status == '1')
                                                    <label class="text-green"> Partnered </label>
                                                @elseif($company->partners->find(Auth::user()->userable->id)->pivot->status == '2')
                                                    {!! Form::open(array('route' => 'schools.accept')) !!}

                                                        {!! Form::hidden('company_id', $company->id) !!}
                                                        {!! Form::submit('Confirm',['class'=>'btn btn-primary'])!!}

                                                    {!! Form::close() !!}

                                                @elseif($company->partners->find(Auth::user()->userable->id)->pivot->status == '3')
                                                    <label class="text-yellow"> Pending... </label>
                                                @endif
                                            @else
                                                <button type="submit" class="btn  btn-danger btn-cancel" data-toggle="modal" data-target="#model-{{ $id }}" title="Partner"> Partner </button>

                                                <div class="modal" id="model-{{ $id }}" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel" tabindex="">
                                                    <div class="modal-dialog box box-danger" >
                                                        <div class="modal-content">
                                                          <div class="modal-header-del">
                                                              <h3 class="modal-del-text"><center> Are you sure you want to partner <br />{{ $company->name }}? </center></h3>
                                                          </div>
                                                          <div class="modal-footer">
                                                                <center>
                                                                    <div class="action-btns2">
                                                                        {!! Form::open(array('route' => 'schools.partner')) !!}

                                                                            {!! Form::hidden('company_id', $company->id) !!}
                                                                            {!! Form::submit('Yes',['class'=>'btn btn-primary btn-del-yes'])!!}

                                                                        {!! Form::close() !!}
                                                                    </div>
                                                                    <div class="action-btns2">
                                                                        <button type="button" class="btn btn-primary btn-del-no" data-toggle="modal" data-target="#model-{{ $id }}">No</button>
                                                                    </div>
                                                                </center>
                                                          </div>
                                                        </div>
                                                    </div>
                                                </div> <!-- modal close-->
                                            @endif
                                        </center>
                                    </td>
                                @endif
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
        </section>
    </div><!-- /.col -->

@endsection

resources/views/companies/jobPost.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
  <!-- Content Wrapper. Contains page content -->


  <div class="content-wrapper">
    <!-- Content Header (Page header) -->

    <!-- Main content -->
    <section class="content">
        <!-- Your Page Content Here -->
        @include('layouts.master-content')
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
@endsection

resources/views/companies/show.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            <div class="row">
                <div class="col-md-7 col-md-offset-1">
                    <!-- Profile Image -->
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                            <div class="row">
                                <div class="col-md-4">
                                    @if(!empty($company->user->image))
                                        <img src="{{ asset('img/profilepics/' . $company->user->image) }}" class="img-responsive thumbnail" alt="User profile picture">
                                    @else
                                        <img src="{{ asset('dist/img/avatar-default-company.png') }}" class="img-responsive thumbnail" alt="User profile picture">
                                    @endif
                                </div>
                                <div class="col-md-8">
                                    @if(Auth::check())
                                        @if(Auth::user()->id === $company->user->id)
                                            <a href="{{ URL::to('/' . $company->user->id) . '/edit' }}"><i class="fa fa-edit pull-right"> Edit </i></a>
                                        @endif
                                    @endif
                                    <h3 class="profile-username"> {{ $company->name  }} </h3>

                                    <strong>Address</strong>
                                    <p class="text-muted">
                                        {{ $company->address }}
                                    </p>

                                    <strong>Contact</strong>
                                    <p class="text-muted">
                                        {{ $company->tel_no }}
                                    </p>

                                    <strong>Email</strong>
                                    <p class="text-muted">
                                        {{ $company->user->email }}
                                    </p>

                                    @if(!empty($company->website))
                                        <strong>Website</strong>
                                        <p class="text-muted">
                                            {{ $company->website }}
                                        </p>
                                    @endif
                                </div>
                            </div>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->

                    @if(!empty($company->description))
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><i class="fa fa-user-plus margin-r-5"></i>About {{ $company->name }}</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <p>
                                    {{ $company->description }}
                                </p>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    @endif

                </div> <!-- col-md- -->

                <div class="col-md-4">
                    <div class="box box-info">
                        <div class="box-header with-border">
                          <font class="box-title text-muted recom-h"><i class="fa fa-circle-o"></i> Partners </font>
                        </div><!-- /.box-header -->

                        <div class="table-responsive">


                        </div><!-- /.table-responsive -->
                    </div>  <!-- box -->
                </div>  <!-- col-md-4 -->

            </div> <!-- row -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection