app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Index
Route::get('/', 'JobsController@index');

//for testing

// Route::get('job_posts/jobview','PagesController@jobview');
// Route::get('job_posts/jobcreate','PagesController@jobcreate');
// Route::get('job_posts/jobedit','PagesController@jobedit');

// Route::get('recommendation/students', 'PagesController@recommendStudents');

// PagesController
Route::get('company/show', 'PagesController@companyShow');
Route::get('dean/show', 'PagesController@deanShow');
Route::get('company/edit', 'PagesController@companyEdit');
Route::get('students/joblists', 'PagesController@jobLists');
Route::get('students/companylists', 'PagesController@companyLists');
Route::get('students/schoollists', 'PagesController@SchoolLists');

Route::get('schools/show','PagesController@schoolShow');
Route::get('schools/edit','PagesController@schoolEdit');

// Route::get('admin/index', 'PagesController@adminIndex');
// Route::get('admin/students', 'PagesController@adminStudentLists');
// Route::get('admin/companies', 'PagesController@adminCompanyLists');
// Route::get('admin/schools', 'PagesController@adminSchoolLists');
// Route::get('admin/faculties', 'PagesController@adminFacultyLists');
// Route::get('admin/jobs', 'PagesController@adminJobLists');
// Route::get('admin/applications', 'PagesController@admingAppLists');
// Route::get('admin/applications', 'PagesController@adminRecommendLists');
// Route::get('admin/categories', 'PagesController@adminCategoryLists');
// Route::get('admin/categories/create', 'PagesController@adminCreateCategories');


// Authentication
Route::get('about', 'PagesController@about');

Route::get('preregister', 'Auth\AuthController@preregister');
Route::post('preregister', 'Auth\AuthController@registerByUserType');
Route::get('register/admin', 'Auth\AuthController@registerAsAdmin');
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister');
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::get('admin/students', 'StudentsController@index');
// Admin Routes
Route::group(['namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::resource('categories', 'CategoriesController');
    Route::get('admin/students', 'StudentsController@index');
    Route::get('admin/schools', 'SchoolsController@index');
    Route::get('admin/faculties', 'FacultiesController@index');
    Route::get('admin/companies', 'CompaniesController@index');
    Route::get('admin/applications', 'ApplicationsController@index');
    Route::get('admin/pending-applications', 'ApplicationsController@showPendingApplications');
    Route::get('admin/successful-applications', 'ApplicationsController@showSuccessfulApplications');
    Route::get('admin/declined-applications', 'ApplicationsController@declinedApplications');
    Route::get('admin/recommendations', 'RecommendationsController@index');
    Route::get('admin/jobs', 'JobsController@index');
    Route::get('admin/active-jobs', 'JobsController@activeJobs');
    Route::get('admin/expired-jobs', 'JobsController@expiredJobs');
    Route::post('admin/jobs/retrieve/{id}', array('as' => 'jobs.retrieve', 'uses' => 'JobsController@retrieve'));
    Route::delete('admin/jobs/destroy/{id}', array('as' => 'jobs.forcedelete', 'uses' => 'JobsController@destroy'));
    Route::delete('admin/jobs/delete/{id}', array('as' => 'jobs.delete', 'uses' => 'JobsController@setJobAsExpired'));
    Route::delete('admin/users/delete/{id}', array('as' => 'admin.delete', 'uses' => 'UsersController@destroy'));
    Route::post('admin/users/retrieve/{id}', array('as' => 'admin.retrieve', 'uses' => 'UsersController@retrieve'));
    Route::delete('admin/users/force-delete/{id}', array('as' => 'admin.forcedelete', 'uses' => 'UsersController@forceDelete'));
});


// NOTE: Resource routes must be at the top of User Routes to avoid being overridden
// Job Posts Routes
Route::post('jobs/apply', ['as' => 'jobs.apply', 'uses' => 'JobsController@apply']);
Route::post('jobs/cancel', ['as' => 'jobs.cancel', 'uses' => 'JobsController@cancelApplication']);
Route::get('jobs/category/{id}', ['as' => 'jobs.category', 'uses' => 'JobsController@getJobsByCategory']);
Route::resource('jobs', 'JobsController');

// Faculty Routes
Route::resource('faculties', 'FacultiesController');

// Student Routes
Route::get('students/skills/{name}', 'StudentsController@studentsBySkill');
Route::resource('students', 'StudentsController');

// Companies Routes
Route::post('companies/partner', ['as' => 'companies.partner', 'uses' => 'CompaniesController@requestPartnership']);
Route::post('companies/accept', ['as' => 'companies.accept', 'uses' => 'CompaniesController@acceptPartnership']);
Route::get('companies/{id}/jobs', ['as' => 'companies.posts', 'uses' => 'CompaniesController@getJobsPosted']);
Route::resource('companies', 'CompaniesController');

// Schools Routes
Route::post('schools/partner', ['as' => 'schools.partner', 'uses' => 'SchoolsController@requestPartnership']);
Route::post('schools/accept', ['as' => 'schools.accept', 'uses' => 'SchoolsController@acceptPartnership']);
Route::resource('schools', 'SchoolsController');

// Application Routes
Route::get('/applications', ['as' => 'application.index', 'uses' => 'ApplicationsController@index']);

// Recommendation Routes
Route::post('recommendations/students', 'RecommendationsController@recommendStudent');
Route::get('recommendations/students', 'RecommendationsController@getStudents');
Route::get('recommendations/student/{id}', 'RecommendationsController@viewRecommendationsOfStudent');
Route::resource('recommendations', 'RecommendationsController');

// Partnership Routes
Route::resource('partnerships', 'PartnershipsController');

// User Routes
Route::get('/{id}', ['as' => 'users.show', 'uses' => 'UserController@show']);
Route::get('/{id}/edit', 'UserController@edit');
Route::put('/{id}', 'UserController@update');


//testin login
// Route::get('login','PagesController@login');
// Route::get('register','PagesController@register');
// Route::get('preregister','PagesController@preregister');
// Route::post('preregister', 'PagesController@userType');

app/Http/Controllers/Admin/FacultiesController.php
<?php

namespace sidelines\Http\Controllers\Admin;

use Illuminate\Http\Request;

use sidelines\DeanFaculty;
use sidelines\Http\Requests;
use sidelines\Http\Controllers\Controller;

class FacultiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faculties = DeanFaculty::with('user')->get();

        return view('admin._facultyLists', compact('faculties'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $faculty = DeanFaculty::find($id);

        $faculty->user->destroy();
        $faculty->destroy();
    }
}

app/Http/Controllers/FacultiesController.php
<?php

namespace sidelines\Http\Controllers;

use Illuminate\Http\Request;

use sidelines\Http\Requests;
use sidelines\Http\Controllers\Controller;
use sidelines\DeanFaculty;

class FacultiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('layouts.master-content');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $faculty = DeanFaculty::find($id);

        return view('users.show', compact('faculty'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faculty =  DeanFaculty::find($id);

        return view('users.edit', compact('faculty'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $faculty =  DeanFaculty::find($id);

        if(count($request->all()) > 0)
        {
            if(!empty($request->file('image')))
            {
                $image = $request->file('image');
                $filename  = time() . rand(1, 9999) . '.' . $image->getClientOriginalExtension();

                $request->file('image')->move(
                    base_path() . '/public/img/profilepics', $filename //pass to image field
                );


                $faculty->user->update([
                    'image' => $filename,
                ]);
                dd($filename);
            }

            $faculty->user->update([
                'email' => $request['email'],
            ]);

            $faculty->update($request->all());

            return \Redirect::route('faculties.show', $id);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/faculties/_sidebarFaculty.blade.php
<li>
    <a href="{{ URL::to('recommendations/students') }}">
        <i class="glyphicon glyphicon-plus text-green"></i> <span class="text-green">Recommend a Student</span>
    </a>
</li>

<hr class="side-hr"/>

<li class="header" style="margin-left: -3px;">Labels</li>

<li>
    <a href="{{ URL::route('schools.index') }}">
        <i class="fa fa-university"></i> <span> Schools </span>
    </a>
</li>

<li>
    <a href="{{ URL::route('companies.index') }}">
        <i class="fa fa-building"></i> <span> Companies </span>
    </a>
</li>
<li>
    <a href="{{ URL::route('application.index') }}">
        <i class="fa fa-user-plus"></i><span> Applications </span>
    </a>
</li>
<li class="#">
    <a href="{{ URL::route('recommendations.index') }}">
         <i class="fa fa-thumbs-up"></i><span> Recommended Students </span>
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-calendar-check-o"></i> <span> Hired Students </span>
    </a>
</li>

resources/views/faculties/edit.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')
@section('content')

<div class="content-wrapper"
    <!-- Main content -->
    <div class="row">
        <section class="content">
           <!-- left column -->
           <div class="col-md-offset-1 col-md-10">
             <!-- general form elements -->
             <div class="box box-primary">
                   <div class="box-header with-border">
                     <h3 class="box-title">Edit Profile</h3>
                   </div><!-- /.box-header -->
                   <!-- form start -->
                     <div class="box-body">
                         <div class="tab-pane" id="settings">
                             {!! Form::model($faculty, array('method' => 'put',
                                                             'route' => ['faculties.update', $faculty->id],
                                                             'class' => 'form form-horizontal',
                                                             'files' => 'true')) !!}

                                  <div class="form-group">
                                      {!! Form::label('profile','Profile Pictures',array('for'=>'inputName','class'=>'col-sm-2 control-label')) !!}
                                      <div class="col-sm-4">
                                          <img class="img-responsive thumbnail" src="{{ asset('img/profilepics/' . $faculty->user->image) }}" alt="User profile picture">
                                          {!! Form::file('image') !!}
                                      </div>
                                  </div>

                                  <div class="form-group">
                                    {!! Form::label('fname', 'First Name', array('for'=>'inputFname','class'=>'col-sm-2 control-label')) !!}
                                    <div class="col-sm-9">
                                     {!! Form::text('fname', $faculty->fname, array('class'=>'form-control', 'id'=>'inputFname')) !!}
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    {!! Form::label('mname', 'Middle Name', array('for'=>'inputMname','class'=>'col-sm-2 control-label')) !!}
                                    <div class="col-sm-9">
                                      {!! Form::text('mname', $faculty->mname, array('class'=>'form-control', 'id'=>'inputMname')) !!}
                                    </div>
                                  </div>
                                  <div class="form-group">
                                      {!! Form::label('lname', 'Last Name',array('class'=>'col-sm-2 control-label','for'=>'inputLname')) !!}
                                    <div class="col-sm-9">
                                      {!! Form::text('lname', $faculty->lname, array('class'=>'form-control')) !!}
                                    </div>
                                  </div>
                                  <div class="form-group">
                                      {!! Form::label('address', 'Address', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                          {!! Form::text('address', $faculty->address, ['class' => 'form-control', 'placeholder' => 'Address'],  'required') !!}
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('dob', 'Birth Date', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                          {!! Form::text('dob', $faculty->date_of_birth, ['class' => 'form-control', 'placeholder' => 'yyyy-mm-dd',  'required']) !!}
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('gender', 'Gender', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                              @if($faculty->gender === 'm')
                                                  <label class="label-font">
                                                      {!! Form::radio('gender', 'm', true, ['class'=>'form-control-gender','required']) !!} Male
                                                  </label>
                                                  <label class="label-font">
                                                      {!! Form::radio('gender', 'f', false, ['class'=>'form-control-gender','required']) !!} Female
                                                  </label>
                                              @else
                                              <label class="label-font">
                                                  {!! Form::radio('gender', 'm', false, ['class'=>'form-control-gender','required']) !!} Male
                                              </label>
                                              <label class="label-font">
                                                  {!! Form::radio('gender', 'f', true, ['class'=>'form-control-gender','required']) !!} Female
                                              </label>
                                              @endif
                                          </label>
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('email', 'Email', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-6">
                                          {!! Form::text('email', $faculty->user->email, ['class' => 'form-control', 'placeholder' => 'Email']) !!}
    									</div>
    									{!! Form::label('contact_no', 'Contact', ['class' => 'col-sm-1 control-label']) !!}
    									<div class="col-sm-2">
    										{!! Form::text('contact_no', $faculty->contact_no, ['class' => 'form-control', 'placeholder' => 'Contact']) !!}
    									</div>
                                  </div>



                                  <div class="page-header with-border">
                                      <h4 class="box-title"> About Me</h4>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('aboutme', 'About Me', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                          {!! Form::textarea('about_me', $faculty->about_me, ['class' => 'form-control', 'placeholder' => 'Type here!']) !!}
                                      </div>
                                  </div>

                                  <div class="page-header with-border">
                                      <h4 class="box-title"> Educational Background </h4>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('education', 'Education', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                          {!! Form::textarea('education', $faculty->education, ['class' => 'form-control', 'placeholder' => 'Type here!']) !!}
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('achievements', 'Achievements', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                          {!! Form::textarea('achievements', $faculty->achievements, ['class' => 'form-control', 'placeholder' => 'Type here!']) !!}
                                      </div>
                                  </div>

                                  <div class="box-header page-header with-border">
                                      <h3 class="box-title"> Seminars Attended </h3>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('seminars', 'Seminars', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                          {!! Form::textarea('seminars', $faculty->seminars, ['class' => 'form-control', 'placeholder' => 'Type here!']) !!}
                                      </div>
                                  </div>


                                  <div class="box-header page-header with-border">
                                      <h4 class="box-title"> Organizations Attended </h4>
                                  </div>

                                  <div class="form-group">
                                      {!! Form::label('organizations', 'Organization', ['class' => 'col-sm-2 control-label']) !!}
                                      <div class="col-sm-9">
                                          {!! Form::textarea('organizations', $faculty->organizations, ['class' => 'form-control', 'placeholder' => 'Type here!']) !!}
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      <div class="col-sm-offset-2 col-sm-10">
                                          {!! Form::submit('Save Changes', ['class'=>'btn btn-primary']) !!}
                                      </div>
                                  </div>
                             {!! Form::close() !!}
                         </div><!-- end of tab-pane -->
                   </div> <!-- end of box-body -->
                </div><!-- /.box -->
            </div> <!-- col-md-offset-1 col-md-11 -->
        </section> <!-- end of section -->
    </div> <!-- end of row  -->
</div> <!-- end of content-wrapper -->

@endsection

resources/views/faculties/show.blade.php
@extends('layouts.master')
@section('title', 'Sidelines')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            <div class="row">
                <div class="col-md-7 col-md-offset-1">
                    <!-- Profile Image -->
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                            <div class="row">
                                <div class="col-md-4">
                                    <img class="img-responsive thumbnail" src="{{ asset('img/profilepics/' . $faculty->user->image) }}" alt="User profile picture">
                                </div>
                                <div class="col-md-8">
                                    <h3 class="profile-username"> {{ $faculty->fname . " " .  $faculty->lname }} - #12103594</h3>

                                    <strong>School Faculty in</strong>
                                    <p class="text-muted">
                                      {{ $faculty->school->name }}
                                    </p>
                                    <strong>Birthdate</strong>
                                    <p class="text-muted">
                                      {{ $faculty->date_of_birth }}
                                    </p>

                                    <strong>Email</strong>
                                    <p class="text-muted">
                                        {{ $faculty->user->email }}
                                    </p>
                                </div>
                            </div>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->

                    @if(!empty($faculty->about_me))
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><i class="fa fa-user-plus margin-r-5"></i>About Me</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <p>
                                    {{ $faculty->about_me }}
                                </p>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    @endif

                    @if(!empty($faculty->education))
                        <div class="box box-primary">
                            <div class="box-header with-border">
                              <h3 class="box-title"><i class="fa   fa-graduation-cap margin-r-5"></i>  Education</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <p>
                                    {{ $faculty->education }}
                                </p>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    @endif

                    @if(!empty($faculty->achievements))
                        <div class="box box-primary">
                            <div class="box-header with-border">
                              <h3 class="box-title"><i class="fa fa-star margin-r-5"></i>Achievements</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                  <p>
                                      {{ $faculty->achievements }}
                                  </p>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    @endif

                    @if(!empty($faculty->achievements))
                        <div class="box box-primary">
                            <div class="box-header with-border">
                              <h3 class="box-title"><i class="fa fa-book margin-r-5"></i>Seminars</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                  <p>
                                      {{ $faculty->seminars }}
                                  </p>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    @endif

                    @if(!empty($faculty->achievements))
                        <div class="box box-primary">
                            <div class="box-header with-border">
                              <h3 class="box-title"><i class="fa  fa-users margin-r-5"></i>Organizations</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                  <p>
                                      {{ $faculty->organizations }}
                                  </p>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    @endif
                </div>
            </div> <!-- row -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection